stages:
  - build
  - push

variables:
  orderscheduler_IMAGE: 'jfrog.tapsi.doctor/local-docker/orderscheduler'
  orderscheduler_TAG: '${CI_COMMIT_TAG}'
  orderscheduler_SOTOON_IMAGE: 'registry.tapsi.doctor/local-docker/orderscheduler'

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login jfrog.tapsi.doctor -u "$CI_REGISTRY_USER" --password-stdin
  - echo "$CI_REGISTRY_PASSWORD_SOTOON" | docker login registry.tapsi.doctor -u "$CI_REGISTRY_USER_SOTOON" --password-stdin

build_orderscheduler:
  stage: build
  tags:
    - runner2
  script:
    - docker build --no-cache --add-host jfrog.tapsi.doctor:172.27.215.78 -t $orderscheduler_IMAGE:$orderscheduler_TAG -f ./Order/Dockerfile-Scheduler ./Order
  rules:
    - if: '$CI_COMMIT_TAG =~ /^orderscheduler-/' # Runs only for tags starting with 'orderscheduler-'

push_orderscheduler:
  stage: push
  tags:
    - runner2
  script:
    - docker push $orderscheduler_IMAGE:$orderscheduler_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^orderscheduler-/' # Runs only for tags starting with 'orderscheduler-'

push_orderscheduler_to_sotoon:
  stage: push
  tags:
    - runner2
  script:
    # Push the existing image to the Sotoon registry
    - docker tag $orderscheduler_IMAGE:$orderscheduler_TAG $orderscheduler_SOTOON_IMAGE:$orderscheduler_TAG
    - docker push $orderscheduler_SOTOON_IMAGE:$orderscheduler_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^orderscheduler-/' # Runs only for tags starting with 'orderscheduler-'
  when: manual